include:
  - board: bmp_boost
    shield: zen_right
    snippet: "studio-rpc-usb-uart split-central input-trackball-pmw3610 dya-pmw3610-settings input-listener input-split-listener-left-all"
    artifact-name: zen_right_trackball_pmw3610_central
  - board: bmp_boost
    shield: zen_right
    snippet: "studio-rpc-usb-uart split-central input-trackball-paw3222 input-listener input-split-listener-left-all"
    artifact-name: zen_right_trackball_paw3222_central
  - board: bmp_boost
    shield: zen_right
    snippet: "studio-rpc-usb-uart split-central input-trackpad-mini input-listener input-split-listener input-split input-split-listener-left-all"
    artifact-name: zen_right_trackpad_central
  - board: bmp_boost
    shield: zen_left
    snippet: "studio-rpc-usb-uart"
    artifact-name: zen_left_peripheral
  - board: bmp_boost
    shield: zen_left
    snippet: "studio-rpc-usb-uart input-trackball-pmw3610 input-split-left-trackball-pmw3610"
    artifact-name: zen_left_trackball_pmw3610_peripheral
  - board: bmp_boost
    shield: zen_left
    snippet: "studio-rpc-usb-uart input-trackball-paw3222 input-split-left-trackball-paw3222"
    artifact-name: zen_left_trackball_paw3222_peripheral
  - board: bmp_boost
    shield: zen_left
    snippet: "studio-rpc-usb-uart input-trackpad-mini input-split-left-trackpad-mini"
    artifact-name: zen_left_trackpad_peripheral
  - board: bmp_boost
    shield: settings_reset
